### ISSUE TITLE
github action work one day yes and one day no

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/bioceurope2020_tidytranscriptomics#2]
Hello @mblue9 in working on the material Iretested the working master and fails

```
<stdin>:1:10: fatal error: git2.h: No such file or directory
```

if you have time sometime would be great if you could help to resolve yet another github  mystery.

Thanks heaps!

**Comment by mblue9** [comment]
I updated the actions with a newer version from https://github.com/seandavi/BuildABiocWorkshop2020/blob/master/.github/workflows/basic_checks.yaml

which has a bit on installing system dependencies and that seems to have fixed that error here https://github.com/stemangiola/bioceurope2020_tidytranscriptomics/runs/1534465262?check_suite_focus=true

**Comment by mblue9** [comment]
The Docker build failed with same error as above so think also need to add sysmem dependencies to Dockerfile but for the moment I've changed the actions to what was in the original workshop template from Bioc i.e. using Bioc devel docker instead of release  and also installing tidyxxx packages normally (i.e. not from github) to see if that fixes it.

**Comment by mblue9** [comment]
Fixed and have just pushed info on how to launch the workshop (note that there are now 3 tidytranscriptomics workshops in the Bioc cloud so I've include a screenshot to show which one to choose).
Also updated schedule, feel free to edit.
I tested the workshop in the Bioc cloud a couple of days ago and the code ran without error and can test again after the edits are done.

**Comment by stemangiola** [comment]
Maria you are a savior! Tomorrow I will practice the workshop. And start with the change of time zone :)
